-- ============================================================
-- Maxims Interiors API — MariaDB / MySQL schema
-- Safe to re-run: every table uses CREATE TABLE IF NOT EXISTS.
-- Apply with:  npm run db:schema        (uses DATABASE_URL)
--         or:  mysql -u USER -p DBNAME < sql/001-schema.sql
--
-- Conventions
--   id           CHAR(24) hex string (ObjectId-shaped), generated by the app
--   timestamps   DATETIME(3), stored in UTC by the app
--   money        DECIMAL(14,2) naira (the frontend sends/expects naira numbers)
--   arrays/maps  JSON columns (order line items, notes, history, images, tags)
--   refs         CHAR(24) columns, indexed, no FK constraints (same as before)
-- ============================================================

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `users` (
  `id`               CHAR(24)     NOT NULL,
  `email`            VARCHAR(191) NOT NULL,
  `password_hash`    VARCHAR(255) NOT NULL,
  `full_name`        VARCHAR(255) NOT NULL,
  `role`             VARCHAR(32)  NOT NULL DEFAULT 'content_editor',
  `avatar_url`       TEXT         NULL,
  `title`            VARCHAR(255) NULL,
  `phone`            VARCHAR(255) NULL,
  `is_active`        TINYINT(1)   NOT NULL DEFAULT 1,
  `last_seen`        DATETIME(3)  NULL,
  `password_version` INT          NOT NULL DEFAULT 0,
  `created_at`       DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`       DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_users_email` (`email`),
  KEY `ix_users_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `products` (
  `id`            CHAR(24)      NOT NULL,
  `name`          VARCHAR(255)  NOT NULL,
  `slug`          VARCHAR(191)  NOT NULL,
  `description`   TEXT          NULL,
  `price`         DECIMAL(14,2) NOT NULL,
  `compare_price` DECIMAL(14,2) NULL,
  `category`      VARCHAR(191)  NOT NULL,
  `badge`         VARCHAR(255)  NULL,
  `images`        JSON          NULL,
  `cover_image`   TEXT          NULL,
  `stock_qty`     INT           NOT NULL DEFAULT 0,
  `sku`           VARCHAR(255)  NULL,
  `status`        VARCHAR(20)   NOT NULL DEFAULT 'active',
  `is_featured`   TINYINT(1)    NOT NULL DEFAULT 0,
  `sort_order`    INT           NOT NULL DEFAULT 0,
  `tags`          JSON          NULL,
  `created_at`    DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`    DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_products_slug` (`slug`),
  KEY `ix_products_status_category` (`status`, `category`),
  KEY `ix_products_featured` (`is_featured`),
  KEY `ix_products_sort` (`sort_order`, `created_at`),
  KEY `ix_products_name` (`name`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `orders` (
  `id`                CHAR(24)      NOT NULL,
  `order_number`      VARCHAR(40)   NULL,
  `customer_name`     VARCHAR(255)  NOT NULL,
  `customer_email`    VARCHAR(191)  NOT NULL,
  `customer_phone`    VARCHAR(255)  NULL,
  `delivery_address`  TEXT          NULL,
  `city`              VARCHAR(255)  NULL,
  `state`             VARCHAR(255)  NULL,
  `items`             JSON          NULL,
  `subtotal`          DECIMAL(14,2) NOT NULL DEFAULT 0,
  `delivery_fee`      DECIMAL(14,2) NOT NULL DEFAULT 0,
  `total`             DECIMAL(14,2) NOT NULL DEFAULT 0,
  `status`            VARCHAR(32)   NOT NULL DEFAULT 'new',
  `kind`              VARCHAR(10)   NULL DEFAULT 'order',
  `source`            VARCHAR(255)  NULL,
  `service`           VARCHAR(255)  NULL,
  `preferred_contact` VARCHAR(20)   NULL DEFAULT 'phone',
  `payment_method`    VARCHAR(255)  NULL,
  `payment_ref`       VARCHAR(255)  NULL,
  `payment_status`    VARCHAR(32)   NULL DEFAULT 'unpaid',
  `notes`             TEXT          NULL,
  `staff_notes`       JSON          NULL,
  `status_history`    JSON          NULL,
  `assigned_to`       CHAR(24)      NULL,
  `created_at`        DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`        DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_orders_number` (`order_number`),
  KEY `ix_orders_status_kind` (`status`, `kind`),
  KEY `ix_orders_kind` (`kind`),
  KEY `ix_orders_email` (`customer_email`),
  KEY `ix_orders_assigned` (`assigned_to`),
  KEY `ix_orders_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `bulk_requests` (
  `id`               CHAR(24)      NOT NULL,
  `company_name`     TEXT          NOT NULL,
  `contact_name`     TEXT          NOT NULL,
  `email`            TEXT          NOT NULL,
  `phone`            TEXT          NULL,
  `project_type`     TEXT          NULL,
  `product_category` TEXT          NULL,
  `quantity`         TEXT          NULL,
  `budget_range`     TEXT          NULL,
  `message`          TEXT          NULL,
  `status`           VARCHAR(20)   NOT NULL DEFAULT 'new',
  `quote_amount`     DECIMAL(14,2) NULL,
  `quote_notes`      TEXT          NULL,
  `assigned_to`      CHAR(24)      NULL,
  `internal_notes`   TEXT          NULL,
  `created_at`       DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`       DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `ix_bulk_status` (`status`),
  KEY `ix_bulk_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `appointments` (
  `id`             CHAR(24)     NOT NULL,
  `client_name`    VARCHAR(255) NOT NULL,
  `client_email`   VARCHAR(255) NOT NULL,
  `client_phone`   VARCHAR(255) NULL,
  `type`           VARCHAR(255) NULL DEFAULT 'design_consultation',
  `service`        VARCHAR(255) NULL,
  `preferred_date` VARCHAR(32)  NOT NULL,
  `preferred_time` VARCHAR(32)  NOT NULL,
  `duration_mins`  INT          NULL DEFAULT 60,
  `status`         VARCHAR(20)  NOT NULL DEFAULT 'pending',
  `location`       VARCHAR(255) NULL DEFAULT 'showroom',
  `meeting_link`   TEXT         NULL,
  `notes`          TEXT         NULL,
  `internal_notes` TEXT         NULL,
  `assigned_to`    CHAR(24)     NULL,
  `confirmed_at`   DATETIME(3)  NULL,
  `created_at`     DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`     DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `ix_appt_slot` (`preferred_date`, `preferred_time`, `status`),
  KEY `ix_appt_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `messages` (
  `id`         CHAR(24)     NOT NULL,
  `full_name`  VARCHAR(255) NOT NULL,
  `email`      VARCHAR(255) NOT NULL,
  `phone`      VARCHAR(255) NULL,
  `service`    VARCHAR(255) NULL,
  `message`    TEXT         NOT NULL,
  `status`     VARCHAR(20)  NOT NULL DEFAULT 'unread',
  `replied_by` CHAR(24)     NULL,
  `reply_text` TEXT         NULL,
  `replied_at` DATETIME(3)  NULL,
  `created_at` DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `ix_messages_status` (`status`),
  KEY `ix_messages_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `gallery` (
  `id`           CHAR(24)     NOT NULL,
  `title`        VARCHAR(255) NOT NULL,
  `slug`         VARCHAR(191) NOT NULL,
  `category`     VARCHAR(191) NOT NULL,
  `location`     VARCHAR(255) NULL,
  `year`         INT          NULL,
  `grid_size`    VARCHAR(10)  NULL DEFAULT 'small',
  `description`  TEXT         NULL,
  `images`       JSON         NULL,
  `cover_image`  TEXT         NULL,
  `is_featured`  TINYINT(1)   NOT NULL DEFAULT 0,
  `is_published` TINYINT(1)   NOT NULL DEFAULT 1,
  `sort_order`   INT          NOT NULL DEFAULT 0,
  `sqft`         VARCHAR(255) NULL,
  `duration`     VARCHAR(255) NULL,
  `client_name`  VARCHAR(255) NULL,
  `created_at`   DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`   DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_gallery_slug` (`slug`),
  KEY `ix_gallery_pub_cat` (`is_published`, `category`),
  KEY `ix_gallery_sort` (`sort_order`, `created_at`),
  KEY `ix_gallery_title` (`title`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `testimonials` (
  `id`           CHAR(24)     NOT NULL,
  `client_name`  VARCHAR(255) NOT NULL,
  `client_role`  VARCHAR(255) NULL,
  `quote`        TEXT         NOT NULL,
  `rating`       INT          NULL DEFAULT 5,
  `project_type` VARCHAR(255) NULL,
  `avatar_url`   TEXT         NULL,
  `is_featured`  TINYINT(1)   NOT NULL DEFAULT 0,
  `is_published` TINYINT(1)   NOT NULL DEFAULT 1,
  `sort_order`   INT          NOT NULL DEFAULT 0,
  `created_at`   DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`   DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `ix_testimonials_pub` (`is_published`, `is_featured`),
  KEY `ix_testimonials_client` (`client_name`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `team_members` (
  `id`           CHAR(24)     NOT NULL,
  `full_name`    VARCHAR(255) NOT NULL,
  `title`        VARCHAR(255) NOT NULL,
  `bio`          TEXT         NULL,
  `photo_url`    TEXT         NULL,
  `instagram`    VARCHAR(255) NULL,
  `linkedin`     VARCHAR(255) NULL,
  `sort_order`   INT          NOT NULL DEFAULT 0,
  `is_published` TINYINT(1)   NOT NULL DEFAULT 1,
  `profile_id`   CHAR(24)     NULL,
  `created_at`   DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`   DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `ix_team_pub_sort` (`is_published`, `sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `settings` (
  `id`         CHAR(24)     NOT NULL,
  `key`        VARCHAR(191) NOT NULL,
  `value`      JSON         NULL,
  `created_at` DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_settings_key` (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `activity` (
  `id`            CHAR(24)     NOT NULL,
  `user_id`       CHAR(24)     NULL,
  `action`        VARCHAR(64)  NOT NULL,
  `resource_type` VARCHAR(64)  NULL,
  `resource_id`   VARCHAR(64)  NULL,
  `description`   TEXT         NULL,
  `created_at`    DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`    DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `ix_activity_created` (`created_at`),
  KEY `ix_activity_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `newsletter` (
  `id`          CHAR(24)     NOT NULL,
  `email`       VARCHAR(191) NOT NULL,
  `name`        VARCHAR(255) NULL,
  `source`      VARCHAR(255) NULL DEFAULT 'website',
  `status`      VARCHAR(20)  NOT NULL DEFAULT 'subscribed',
  `welcomed_at` DATETIME(3)  NULL,
  `created_at`  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_newsletter_email` (`email`),
  KEY `ix_newsletter_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `transactions` (
  `id`               CHAR(24)      NOT NULL,
  `reference`        VARCHAR(191)  NOT NULL,
  `provider`         VARCHAR(20)   NULL DEFAULT 'squad',
  `order_id`         CHAR(24)      NULL,
  `customer_name`    VARCHAR(255)  NULL,
  `customer_email`   VARCHAR(191)  NOT NULL,
  `customer_phone`   VARCHAR(255)  NULL,
  `amount`           DECIMAL(14,2) NOT NULL,
  `currency`         VARCHAR(8)    NULL DEFAULT 'NGN',
  `status`           VARCHAR(20)   NOT NULL DEFAULT 'pending',
  `channel`          VARCHAR(255)  NULL,
  `description`      TEXT          NULL,
  `gateway_response` TEXT          NULL,
  `metadata`         JSON          NULL,
  `paid_at`          DATETIME(3)   NULL,
  `created_at`       DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`       DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_transactions_reference` (`reference`),
  KEY `ix_transactions_status` (`status`),
  KEY `ix_transactions_order` (`order_id`),
  KEY `ix_transactions_email` (`customer_email`),
  KEY `ix_transactions_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
